services:
  - type: web
    name: task-manager
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: Task Manager
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: LOG_CHANNEL
        value: stderr
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        fromService:
          type: web
          name: task-manager
          property: url
      - key: DATABASE_URL
        fromDatabase:
          name: task-manager-db
          property: connectionString
      - key: DB_CONNECTION
        value: pgsql
      - key: COMPOSER_MEMORY_LIMIT
        value: -1

databases:
  - name: task-manager-db
    plan: free